# Generated by Django 3.0.7 on 2024-08-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20240830_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('MUM', 'Mumbai'), ('DEL', 'Delhi'), ('BLR', 'Bangalore'), ('HYD', 'Hyderabad'), ('CHN', 'Chennai'), ('KOL', 'Kolkata'), ('PUN', 'Pune'), ('AMD', 'Ahmedabad'), ('SUR', 'Surat'), ('JPR', 'Jaipur'), ('LKO', 'Lucknow'), ('KNU', 'Kanpur'), ('NGP', 'Nagpur'), ('IND', 'Indore'), ('BPL', 'Bhopal'), ('CBE', 'Coimbatore'), ('VD', 'Vadodara'), ('VSKP', 'Visakhapatnam'), ('PAT', 'Patna'), ('RK', 'Rajkot'), ('VNS', 'Varanasi'), ('SRN', 'Srinagar'), ('TVM', 'Thiruvananthapuram'), ('BBSR', 'Bhubaneswar'), ('RPR', 'Raipur'), ('RNC', 'Ranchi'), ('AUR', 'Aurangabad'), ('GUR', 'Gurgaon'), ('NOI', 'Noida'), ('FRD', 'Faridabad'), ('GZB', 'Ghaziabad'), ('MYS', 'Mysore'), ('JLD', 'Jalandhar'), ('LDH', 'Ludhiana'), ('ASR', 'Amritsar'), ('CHD', 'Chandigarh'), ('DDN', 'Dehradun'), ('GWH', 'Guwahati'), ('IMP', 'Imphal'), ('SHL', 'Shillong'), ('AZL', 'Aizawl'), ('KHM', 'Kohima'), ('BBSR', 'Bhubaneswar'), ('ITN', 'Itanagar'), ('GNG', 'Gangtok'), ('PNJ', 'Panaji'), ('PBL', 'Port Blair')], max_length=100),
        ),
    ]
