# Generated by Django 3.0.7 on 2024-08-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20240831_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('Mumbai', 'Mumbai'), ('Delhi', 'Delhi'), ('Bangalore', 'Bangalore'), ('Hyderabad', 'Hyderabad'), ('Chennai', 'Chennai'), ('Kolkata', 'Kolkata'), ('Pune', 'Pune'), ('Ahmedabad', 'Ahmedabad'), ('Surat', 'Surat'), ('Jaipur', 'Jaipur'), ('Lucknow', 'Lucknow'), ('Kanpur', 'Kanpur'), ('Nagpur', 'Nagpur'), ('Indore', 'Indore'), ('Bhopal', 'Bhopal'), ('Coimbatore', 'Coimbatore'), ('Vadodara', 'Vadodara'), ('Visakhapatnam', 'Visakhapatnam'), ('Patna', 'Patna'), ('Rajkot', 'Rajkot'), ('Varanasi', 'Varanasi'), ('Srinagar', 'Srinagar'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Bhubaneswar', 'Bhubaneswar'), ('Raipur', 'Raipur'), ('Ranchi', 'Ranchi'), ('Aurangabad', 'Aurangabad'), ('Gurgaon', 'Gurgaon'), ('Noida', 'Noida'), ('Faridabad', 'Faridabad'), ('Ghaziabad', 'Ghaziabad'), ('Mysore', 'Mysore'), ('Jalandhar', 'Jalandhar'), ('Ludhiana', 'Ludhiana'), ('Amritsar', 'Amritsar'), ('Chandigarh', 'Chandigarh'), ('Dehradun', 'Dehradun'), ('Guwahati', 'Guwahati'), ('Imphal', 'Imphal'), ('Shillong', 'Shillong'), ('Aizawl', 'Aizawl'), ('Kohima', 'Kohima'), ('Bhubaneswar', 'Bhubaneswar'), ('Itanagar', 'Itanagar'), ('Gangtok', 'Gangtok'), ('Panaji', 'Panaji'), ('Port Blair', 'Port Blair')], max_length=100),
        ),
    ]
